//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane
{
    using System;
    using System.Collections.Generic;
    
    public partial class dergi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dergi()
        {
            this.islem = new HashSet<islem>();
        }
    
        public int ISSN { get; set; }
        public string ad { get; set; }
        public string YayınEvi { get; set; }
        public Nullable<System.DateTime> sonTarih { get; set; }
        public string kategori { get; set; }
        public string aciklama { get; set; }
        public byte[] fotograf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<islem> islem { get; set; }
    }
}
