//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane
{
    using System;
    using System.Collections.Generic;
    
    public partial class uye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uye()
        {
            this.islem = new HashSet<islem>();
        }
    
        public int uyeID { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string eMail { get; set; }
        public string sifre { get; set; }
        public string telefon { get; set; }
        public string adres { get; set; }
        public int uyelikDurumu { get; set; }
        public int adminID { get; set; }
        public int ParaCezasi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<islem> islem { get; set; }
    }
}
